name: Post commit info to Discourse Chat

on:
  push:
    branches:
      - main

jobs:
  notify-discourse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Gather commit details
        id: format
        run: |
          # Get latest commit SHA
          SHA=$(git rev-parse HEAD)
          
          # Get commit message (title)
          TITLE=$(git log -1 --pretty=format:"%s")
          
          # Get author name
          AUTHOR=$(git log -1 --pretty=format:"%an")
          
          # Get list of files changed (up to 10, truncated for safety)
          FILES=$(git show --pretty="" --name-only | head -10 | sed 's/^/`/;s/$/`/' | paste -sd ", " -)
          
          # Build message
          MSG="🧀**New Commit!**%0A${TITLE}%0AChanged: ${FILES}%0AAuthor: ${AUTHOR}"
          
          echo "message=$MSG" >> $GITHUB_OUTPUT

      - name: Send to Discourse Chat
        env:
          DISCOURSE_WEBHOOK_URL: ${{ secrets.DISCOURSE_WEBHOOK_URL }}
        run: |
          curl -s -X POST \
            -H "Content-Type: application/json" \
            -d "{\"text\": \"${{ steps.format.outputs.message }}\"}" \
            "$DISCOURSE_WEBHOOK_URL"
